In [2]:
import pandas as pd

In [5]:
data = pd.read_csv('./data/sub-division_population_of_pakistan.csv')
data

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.00,0.00,0,0.00
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.00,0.00,0,0.00
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.00,0.00,0,0.00
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.00,0.00,0,0.00
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.00,0.00,0,0.00

In [7]:

data.head()

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,BAHAWALNAGAR DISTRICT,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48

In [8]:
data.tail()

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.0,0.0,0,0.0
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.0,0.0,0,0.0
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.0,0.0,0,0.0
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.0,0.0,0,0.0
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,SOUTH WAZIRISTAN DISTRICT,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.0,0.0,0,0.0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528 entries, 0 to 527
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PROVINCE                    528 non-null    object
 1   DIVISION                    528 non-null    object
 2   DISTRICT                    528 non-null    object
 3   SUB DIVISION                528 non-null    object
 4   AREA (sq.km)                528 non-null    float64
 5   ALL SEXES (RURAL)           528 non-null    int64
 6   MALE (RURAL)                528 non-null    int64
 7   FEMALE (RURAL)              528 non-null    int64
 8   TRANSGENDER (RURAL)         528 non-null    int64
 9   SEX RATIO (RURAL)           528 non-null    float64
 10  AVG HOUSEHOLD SIZE (RURAL)  528 non-null    float64
 11  POPULATION 1998 (RURAL)     528 non-null    int64
 12  ANNUAL GROWTH RATE (RURAL)  528 non-null    float64
 13  ALL SEXES (URBAN)           528 non-null    int64
 14  MALE (URBAN)                528 non-null    int64
 15  FEMALE (URBAN)              528 non-null    int64
 16  TRANSGENDER (URBAN)         528 non-null    int64
 17  SEX RATIO (URBAN)           528 non-null    float64
 18  AVG HOUSEHOLD SIZE (URBAN)  528 non-null    float64
 19  POPULATION 1998 (URBAN)     528 non-null    int64
 20  ANNUAL GROWTH RATE (URBAN)  528 non-null    float64
dtypes: float64(7), int64(10), object(4)
memory usage: 86.8+ KB

In [10]:
data.describe()

,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),AVG HOUSEHOLD SIZE (RURAL),POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
count,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000,5.280000e+02,5.280000e+02,5.280000e+02,528.000000,528.000000,528.000000,5.280000e+02,528.000000
mean,1492.005871,2.462780e+05,1.252757e+05,1.209841e+05,18.174242,98.982614,6.277064,1.674280e+05,3.124792,1.408635e+05,7.284339e+04,6.799787e+04,22.276515,75.411269,4.406402,8.014457e+04,1.920814
std,2039.453778,2.711898e+05,1.375630e+05,1.337169e+05,25.522248,26.812660,2.074947,1.783890e+05,9.577872,3.512463e+05,1.823492e+05,1.688725e+05,66.068127,49.687341,2.948336,2.023120e+05,2.098908
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,425.000000,5.093450e+04,2.712725e+04,2.397900e+04,1.000000,101.105000,5.700000,3.527350e+04,1.440000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000
50%,882.000000,1.652410e+05,8.413450e+04,8.204400e+04,10.000000,105.285000,6.310000,1.172065e+05,2.030000,4.325450e+04,2.198000e+04,2.099900e+04,3.000000,103.195000,5.755000,2.129800e+04,1.855000
75%,1734.250000,3.129112e+05,1.605022e+05,1.522190e+05,25.000000,108.347500,7.200000,2.130542e+05,2.812500,1.178148e+05,6.030175e+04,5.746525e+04,19.000000,107.040000,6.340000,6.542225e+04,2.985000
max,18374.000000,2.297375e+06,1.172995e+06,1.124167e+06,213.000000,139.380000,12.430000,1.044035e+06,100.000000,3.653616e+06,1.905921e+06,1.746900e+06,795.000000,297.810000,10.060000,2.075867e+06,19.780000

# 1. Indexing & Selecting Data

In [12]:
# .loc[] for label-based indexing
print("Selecting specific rows and columns using .loc[]")
print(data.loc[0:5, ['AREA (sq.km)', 'ALL SEXES (RURAL)']])

Selecting specific rows and columns using .loc[]
   AREA (sq.km)  ALL SEXES (RURAL)
0        1729.0             619550
1        1500.0             540342
2        2536.0             361240
3        1295.0             382115
4        1818.0             452723
5        1738.0             902476

In [13]:
# .iloc[] for position-based indexing
print("\nSelecting specific rows and columns using .iloc[]")
print(data.iloc[0:5, 0:2])

Selecting specific rows and columns using .iloc[]
  PROVINCE             DIVISION
0   PUNJAB  BAHAWALPUR DIVISION
1   PUNJAB  BAHAWALPUR DIVISION
2   PUNJAB  BAHAWALPUR DIVISION
3   PUNJAB  BAHAWALPUR DIVISION
4   PUNJAB  BAHAWALPUR DIVISION

# Conditional selection

In [15]:
print("\nConditional selection: Rows where 'ALL SEXES (RURAL)' > 100000")
print(data[data['ALL SEXES (RURAL)'] > 100000])

Conditional selection: Rows where 'ALL SEXES (RURAL)' > 100000
     PROVINCE                   DIVISION                   DISTRICT  \
0      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
1      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
2      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
3      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
4      PUNJAB        BAHAWALPUR DIVISION      BAHAWALNAGAR DISTRICT
..        ...                        ...                        ...
511  KPK/FATA             BANNU DIVISION  NORTH WAZIRISTAN DISTRICT
518  KPK/FATA             KOHAT DIVISION           ORAKZAI DISTRICT
520  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
521  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT
527  KPK/FATA  DERA ISMAIL KHAN DIVISION  SOUTH WAZIRISTAN DISTRICT

            SUB DIVISION  AREA (sq.km)  ALL SEXES (RURAL)  MALE (RURAL)  \
0    BAHAWALNAGAR TEHSIL        1729.0             619550        316864
1       CHISHTIAN TEHSIL        1500.0             540342        273788
2      FORT ABBAS TEHSIL        2536.0             361240        182655
3      HAROONABAD TEHSIL        1295.0             382115        192278
4     MINCHINABAD TEHSIL        1818.0             452723        231506
..                   ...           ...                ...           ...
511       MIR ALI TEHSIL         605.0             184986         94496
518         LOWER TEHSIL         565.0             107323         53767
520        BIRMIL TEHSIL         923.0             104282         54323
521         LADHA TEHSIL         466.0             110842         57755
527          WANA TEHSIL        2315.0             153156         81342

     FEMALE (RURAL)  TRANSGENDER (RURAL)  SEX RATIO (RURAL)  ...  \
0            302644                   42             104.70  ...
1            266500                   54             102.73  ...
2            178541                   44             102.30  ...
3            189808                   29             101.30  ...
4            221178                   39             104.67  ...
..              ...                  ...                ...  ...
511           90481                    9             104.44  ...
518           53550                    6             100.41  ...
520           49948                   11             108.76  ...
521           53080                    7             108.81  ...
527           71796                   18             113.30  ...

     POPULATION 1998 (RURAL)  ANNUAL GROWTH RATE (RURAL)  ALL SEXES (URBAN)  \
0                     407768                        2.22             193840
1                     395983                        1.65             149424
2                     250959                        1.93              61528
3                     297343                        1.33             142600
4                     316593                        1.90              72294
..                       ...                         ...                ...
511                    93855                        3.63                  0
518                    65416                        2.63                  0
520                    58512                        3.08                  0
521                    72278                        2.27                  0
527                    90772                        2.79                  0

     MALE (URBAN)  FEMALE (URBAN)  TRANSGENDER (URBAN)  SEX RATIO (URBAN)  \
0           98391           95402                   47             103.13
1           75546           73851                   27             102.30
2           31360           30150                   18             104.01
3           71345           71236                   19             100.15
4           36694           35590                   10             103.10
..            ...             ...                  ...                ...
511             0               0                    0               0.00
518             0               0                    0               0.00
520             0               0                    0               0.00
521             0               0                    0               0.00
527             0               0                    0               0.00

     AVG HOUSEHOLD SIZE (URBAN)  POPULATION 1998 (URBAN)  \
0                          6.02                   133785
1                          6.01                   102287
2                          6.00                    34637
3                          6.02                    84424
4                          6.34                    37668
..                          ...                      ...
511                        0.00                        0
518                        0.00                        0
520                        0.00                        0
521                        0.00                        0
527                        0.00                        0

     ANNUAL GROWTH RATE (URBAN)
0                          1.97
1                          2.01
2                          3.06
3                          2.79
4                          3.48
..                          ...
511                        0.00
518                        0.00
520                        0.00
521                        0.00
527                        0.00

[338 rows x 21 columns]

# 2. Data Cleaning 🧹

In [21]:
# Handling Missing Data
print("\nHandling Missing Data")
# Drop rows with any missing values
data_cleaned = data.dropna()
print("Rows with missing data dropped:", data_cleaned.shape)

# Fill missing values with a specific value (e.g., 0)
data_filled = data.fillna(0)
print("Missing data filled with 0:", data_filled.shape)

Handling Missing Data
Rows with missing data dropped: (528, 21)
Missing data filled with 0: (528, 21)

# Data Type Conversion

In [22]:
print("\nData Type Conversion")
# Convert a column to a specific data type
data['AREA (sq.km)'] = data['AREA (sq.km)'].astype(float)
print("Converted 'AREA (sq.km)' to float")

# Removing Duplicates
print("\nRemoving Duplicates")
data_no_duplicates = data.drop_duplicates()
print("Removed duplicates:", data_no_duplicates.shape)

Data Type Conversion
Converted 'AREA (sq.km)' to float

Removing Duplicates
Removed duplicates: (528, 21)

# 3. Data Manipulation & Analysis 📈

In [29]:
# Aggregation
print("\nAggregation")
# Group by a column and aggregate
grouped = data.groupby('AREA (sq.km)').agg({'ALL SEXES (RURAL)': 'sum'})
print("Aggregated data by 'AREA (sq.km)':")
print(grouped.head())

# String Operations
print("\nString Operations")
# Example of string operations on a Series
data['DISTRICT'] = data['DISTRICT'].str.lower()
print("Converted 'District' names to uppercase")

# Merging, Joining, and Concatenating
print("\nMerging, Joining, and Concatenating")
# Example of concatenating two DataFrames
df_concat = pd.concat([data, data], axis=0)
print("Concatenated DataFrame with itself")

# Reshaping Data
print("\nReshaping Data")
# Pivot example
pivoted = data.pivot_table(index='AREA (sq.km)', columns='DISTRICT', values='ALL SEXES (RURAL)', aggfunc='sum')
print("Pivoted data:")
print(pivoted.head())

Aggregation
Aggregated data by 'AREA (sq.km)':
              ALL SEXES (RURAL)
AREA (sq.km)
0.0                      126832
4.0                           0
6.0                           0
8.0                           0
9.0                           0

String Operations
Converted 'District' names to uppercase

Merging, Joining, and Concatenating
Concatenated DataFrame with itself

Reshaping Data
Pivoted data:
DISTRICT      abbottabad district  attock district  awaran district  \
AREA (sq.km)
0.0                           NaN              NaN              NaN
4.0                           NaN              NaN              NaN
6.0                           NaN              NaN              NaN
8.0                           NaN              NaN              NaN
9.0                           NaN              NaN              NaN

DISTRICT      badin district  bahawalnagar district  bahawalpur district  \
AREA (sq.km)
0.0                      NaN                    NaN                  NaN
4.0                      NaN                    NaN                  NaN
6.0                      NaN                    NaN                  NaN
8.0                      NaN                    NaN                  NaN
9.0                      NaN                    NaN                  NaN

DISTRICT      bajaur district  bannu district  barkhan district  \
AREA (sq.km)
0.0                       NaN             NaN               NaN
4.0                       NaN             NaN               NaN
6.0                       NaN             NaN               NaN
8.0                       NaN             NaN               NaN
9.0                       NaN             NaN               NaN

DISTRICT      bhakkar district  ...  tharparkar district  thatta district  \
AREA (sq.km)                    ...
0.0                        NaN  ...                  NaN              NaN
4.0                        NaN  ...                  NaN              NaN
6.0                        NaN  ...                  NaN              NaN
8.0                        NaN  ...                  NaN              NaN
9.0                        NaN  ...                  NaN              NaN

DISTRICT      toba tek singh district  torghar district  umer kot district  \
AREA (sq.km)
0.0                               NaN               NaN                NaN
4.0                               NaN               NaN                NaN
6.0                               NaN               NaN                NaN
8.0                               NaN               NaN                NaN
9.0                               NaN               NaN                NaN

DISTRICT      upper dir district  vehari district  washuk district  \
AREA (sq.km)
0.0                          NaN              NaN              NaN
4.0                          NaN              NaN              NaN
6.0                          NaN              NaN              NaN
8.0                          NaN              NaN              NaN
9.0                          NaN              NaN              NaN

DISTRICT      zhob district  ziarat district
AREA (sq.km)
0.0                     NaN              NaN
4.0                     NaN              NaN
6.0                     NaN              NaN
8.0                     NaN              NaN
9.0                     NaN              NaN

[5 rows x 131 columns]

In [34]:
data

,PROVINCE,DIVISION,DISTRICT,SUB DIVISION,AREA (sq.km),ALL SEXES (RURAL),MALE (RURAL),FEMALE (RURAL),TRANSGENDER (RURAL),SEX RATIO (RURAL),...,POPULATION 1998 (RURAL),ANNUAL GROWTH RATE (RURAL),ALL SEXES (URBAN),MALE (URBAN),FEMALE (URBAN),TRANSGENDER (URBAN),SEX RATIO (URBAN),AVG HOUSEHOLD SIZE (URBAN),POPULATION 1998 (URBAN),ANNUAL GROWTH RATE (URBAN)
0,PUNJAB,BAHAWALPUR DIVISION,bahawalnagar district,BAHAWALNAGAR TEHSIL,1729.0,619550,316864,302644,42,104.70,...,407768,2.22,193840,98391,95402,47,103.13,6.02,133785,1.97
1,PUNJAB,BAHAWALPUR DIVISION,bahawalnagar district,CHISHTIAN TEHSIL,1500.0,540342,273788,266500,54,102.73,...,395983,1.65,149424,75546,73851,27,102.30,6.01,102287,2.01
2,PUNJAB,BAHAWALPUR DIVISION,bahawalnagar district,FORT ABBAS TEHSIL,2536.0,361240,182655,178541,44,102.30,...,250959,1.93,61528,31360,30150,18,104.01,6.00,34637,3.06
3,PUNJAB,BAHAWALPUR DIVISION,bahawalnagar district,HAROONABAD TEHSIL,1295.0,382115,192278,189808,29,101.30,...,297343,1.33,142600,71345,71236,19,100.15,6.02,84424,2.79
4,PUNJAB,BAHAWALPUR DIVISION,bahawalnagar district,MINCHINABAD TEHSIL,1818.0,452723,231506,221178,39,104.67,...,316593,1.90,72294,36694,35590,10,103.10,6.34,37668,3.48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
523,KPK/FATA,DERA ISMAIL KHAN DIVISION,south waziristan district,SARAROGHA TEHSIL,813.0,98180,51479,46694,7,110.25,...,72063,1.64,0,0,0,0,0.00,0.00,0,0.00
524,KPK/FATA,DERA ISMAIL KHAN DIVISION,south waziristan district,SERWEKAI TEHSIL,398.0,54540,28695,25844,1,111.03,...,31472,2.93,0,0,0,0,0.00,0.00,0,0.00
525,KPK/FATA,DERA ISMAIL KHAN DIVISION,south waziristan district,TIARZA TEHSIL,734.0,45156,23649,21507,0,109.96,...,37708,0.95,0,0,0,0,0.00,0.00,0,0.00
526,KPK/FATA,DERA ISMAIL KHAN DIVISION,south waziristan district,TOI KHULLA TEHSIL,567.0,50413,27462,22947,4,119.68,...,36508,1.71,0,0,0,0,0.00,0.00,0,0.00
527,KPK/FATA,DERA ISMAIL KHAN DIVISION,south waziristan district,WANA TEHSIL,2315.0,153156,81342,71796,18,113.30,...,90772,2.79,0,0,0,0,0.00,0.00,0,0.00